"""Initial tables

Revision ID: 2dfb05c7fd57
Revises: 
Create Date: 2026-04-20 13:13:47.433221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dfb05c7fd57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('menu_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('menu_id'),
    sa.UniqueConstraint('menu_name')
    )
    op.create_table('tables',
    sa.Column('table_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('table_num', sa.Integer(), nullable=False),
    sa.Column('grid_row', sa.Integer(), nullable=False),
    sa.Column('grid_col', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('grid_row', 'grid_col', name='uq_table_grid_pos'),
    sa.UniqueConstraint('table_num')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], name='FK_customers_tables'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('depositor', sa.String(length=50), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='FK_orders_customers'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.BigInteger(), nullable=False),
    sa.Column('selected_option', sa.String(length=50), nullable=True),
    sa.Column('is_served', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], name='FK_order_items_menus'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='FK_order_items_orders'),
    sa.PrimaryKeyConstraint('order_id', 'menu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('tables')
    op.drop_table('menus')
    # ### end Alembic commands ###
