"""add title to metadata

Revision ID: 6af903e92a18
Revises: a6b1c2d3e4f5
Create Date: 2026-05-17 18:45:05.935274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af903e92a18'
down_revision: Union[str, Sequence[str], None] = 'a6b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('title', sa.String(length=100), server_default=sa.text("'그루터기 일일호프'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'title')
    # ### end Alembic commands ###
