"""Add index to Menu and unique constraint

Revision ID: a61e5b7590fa
Revises: dde92fc1b3ec
Create Date: 2026-05-11 01:43:07.004696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61e5b7590fa'
down_revision: Union[str, Sequence[str], None] = 'dde92fc1b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('index', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_section_index', 'menus', ['section', 'index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_section_index', 'menus', type_='unique')
    op.drop_column('menus', 'index')
    # ### end Alembic commands ###
