"""make menu_id optional in order_items for menu deletion

Revision ID: dde92fc1b3ec
Revises: dbc53cbccdff
Create Date: 2026-05-11 00:55:04.981530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde92fc1b3ec'
down_revision: Union[str, Sequence[str], None] = 'dbc53cbccdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'menu_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('FK_order_items_menus'), 'order_items', type_='foreignkey')
    op.create_foreign_key('FK_order_items_menus', 'order_items', 'menus', ['menu_id'], ['menu_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_order_items_menus', 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('FK_order_items_menus'), 'order_items', 'menus', ['menu_id'], ['menu_id'])
    op.alter_column('order_items', 'menu_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
