"""Add check constraint and make table_id nullable

Revision ID: e23bbe198c1e
Revises: 2dfb05c7fd57
Create Date: 2026-05-09 07:39:03.350068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e23bbe198c1e"
down_revision: Union[str, Sequence[str], None] = "2dfb05c7fd57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("customers", "table_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("FK_customers_tables"), "customers", type_="foreignkey")
    op.create_foreign_key(
        "FK_customers_tables",
        "customers",
        "tables",
        ["table_id"],
        ["table_id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint("check_quantity_positive", "order_items", "quantity > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_quantity_positive", "order_items", type_="check")
    op.drop_constraint("FK_customers_tables", "customers", type_="foreignkey")
    op.create_foreign_key(
        op.f("FK_customers_tables"), "customers", "tables", ["table_id"], ["table_id"]
    )
    op.alter_column("customers", "table_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
