"""add section to menus

Revision ID: ec982905412a
Revises: e23bbe198c1e
Create Date: 2026-05-09 10:05:48.618292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec982905412a'
down_revision: Union[str, Sequence[str], None] = 'e23bbe198c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('section', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'section')
    # ### end Alembic commands ###
